### ISSUE TITLE
Instructions to run code example

### ISSUE THREAD

**Issue by jwalanta** [boombuler/led#2]
Can you please provide instructions to run the code example in readme? I tried running this on osx, and it gave me (with Busylight Lync plugged): 
```
src/github.com/boombuler/hid/hid_darwin.go:262: cannot take the address of _Cgo_ptr(_Cfpvar_fp_deviceUnpluged)
```

**Comment by boombuler** [comment]
Hi,

this looks like an issue in the hid lib. 
Would you mind to test if it works if you change the following line 
github.com/boombuler/hid/hid_darwin.go (line 262)
from 
`C.IOHIDDeviceRegisterRemovalCallback(device, (*[0]byte)(unsafe.Pointer(&C.deviceUnpluged)), unsafe.Pointer(dev))`
to 
`C.IOHIDDeviceRegisterRemovalCallback(device, (*[0]byte)(unsafe.Pointer(C.deviceUnpluged)), unsafe.Pointer(dev))`

**Comment by jwalanta** [comment]
It runs now, but the leds are still not lighting up. I'm debugging, will let you know if i find something.

**Comment by boombuler** [comment]
Hi again,
the creatator of NotifierLight changed his code for BusyLight Lync because some devices didn't work with the given data.

You could try to Change busylight.go Line 36 to
`d.Write([]byte{0x00, 0x00, 0x00, byte(r >> 8), byte(g >> 8), byte(b >> 8), 0x00, 0x00, 0x00})`

seems to be some problem with some hardware revisions. Could you try and give feedback?

**Comment by jwalanta** [comment]
It worked! Thank you.
